general:
  # Commands to run when the WM has started. This is useful for running a
  # script or launching another application.
  # Example: The below command launches Zebar.
  startup_commands: ['shell-exec zebar']

  # Commands to run just before the WM is shutdown.
  # Example: The below command kills Zebar.
  shutdown_commands: ['shell-exec taskkill /IM zebar.exe /F']

  # Commands to run after the WM config is reloaded.
  config_reload_commands: []

  # Whether to automatically focus windows underneath the cursor.
  focus_follows_cursor: false

  # Whether to switch back and forth between the previously focused
  # workspace when focusing the current workspace.
  toggle_workspace_on_refocus: false

  cursor_jump:
    # Whether to automatically move the cursor on the specified trigger.
    enabled: true

    # Trigger for cursor jump:
    # - 'monitor_focus': Jump when focus changes between monitors.
    # - 'window_focus': Jump when focus changes between windows.
    trigger: 'monitor_focus'

  # How windows should be hidden when switching workspaces.
  # - 'cloak': Recommended. Hides windows with no animation.
  # - 'hide': Legacy method (v3.5 and earlier) that has a brief animation,
  # but has stability issues with some apps.
  hide_method: 'cloak'

  # Affects which windows get shown in the native Windows taskbar. Has no
  # effect if `hide_method: 'hide'`.
  # - 'true': Show all windows (regardless of workspace).
  # - 'false': Only show windows from the currently shown workspaces.
  show_all_in_taskbar: false

gaps:
  # Whether to scale the gaps with the DPI of the monitor.
  scale_with_dpi: true

  # Gap between adjacent windows.
  inner_gap: '20px'

  # Gap between windows and the screen edge.
  outer_gap:
    top: '60px'
    right: '20px'
    bottom: '20px'
    left: '20px'

window_effects:
  # Visual effects to apply to the focused window.
  focused_window:
    # Highlight the window with a colored border.
    # ** Exclusive to Windows 11 due to API limitations.
    border:
      enabled: true
      color: '#8dbcff'

    # Remove the title bar from the window's frame. Note that this can
    # cause rendering issues for some applications.
    hide_title_bar:
      enabled: false

    # Change the corner style of the window's frame.
    # ** Exclusive to Windows 11 due to API limitations.
    corner_style:
      enabled: false
      # Allowed values: 'square', 'rounded', 'small_rounded'.
      style: 'square'

    # Change the transparency of the window.
    transparency:
      enabled: false
      # Can be something like '95%' or '0.95' for slightly transparent windows.
      # '0' or '0%' is fully transparent (and, by consequence, unfocusable).
      opacity: '95%'

  # Visual effects to apply to non-focused windows.
  other_windows:
    border:
      enabled: true
      color: '#a1a1a1'
    hide_title_bar:
      enabled: false
    corner_style:
      enabled: false
      style: 'square'
    transparency:
      enabled: false
      opacity: '0%'

window_behavior:
  # New windows are created in this state whenever possible.
  # Allowed values: 'tiling', 'floating'.
  initial_state: 'tiling'

  # Sets the default options for when a new window is created. This also
  # changes the defaults for when the state change commands, like
  # `set-floating`, are used without any flags.
  state_defaults:
    floating:
      # Whether to center floating windows by default.
      centered: true

      # Whether to show floating windows as always on top.
      shown_on_top: false

    fullscreen:
      # Maximize the window if possible. If the window doesn't have a
      # maximize button, then it'll be fullscreen'ed normally instead.
      maximized: false

      # Whether to show fullscreen windows as always on top.
      shown_on_top: false

workspaces:
  - name: '1'
    display_name: "1. Main/Coding"
    bind_to_monitor: 0
  - name: '2'
    display_name: "2. Notes/GPT (work)"
  - name: '3'
    display_name: "3. Chats/Email (work)"
  - name: '4'
    display_name: "4. Tasks"
  - name: '5'
    display_name: "5. Fun"
  - name: '6'
    display_name: "6. Notes/GPT (personal)"
  - name: '7'
    display_name: "7. Chats/Email (personal)"
  - name: '8'
    display_name: "8. Gaming"
    bind_to_monitor: 0


window_rules:
  - commands: ["move --workspace 3"]
    match:
      # Move browsers to workspace .
      - window_process: { regex: "teams" }


  - commands: ['ignore']
    match:
      # Ignores any Zebar windows.
      - window_process: { equals: 'zebar' }

      # Ignores picture-in-picture windows for browsers.
      - window_title: { regex: '[Pp]icture.in.[Pp]icture' }
        window_class: { regex: 'Chrome_WidgetWin_1|MozillaDialogClass' }

      # Ignore rules for various 3rd-party apps.
      - window_process: { equals: 'PowerToys' }
        window_class: { regex: 'HwndWrapper\[PowerToys\.PowerAccent.*?\]' }
      - window_process: { equals: 'PowerToys' }
        window_title: { regex: '.*? - Peek' }
      - window_process: { equals: 'Lively' }
        window_class: { regex: 'HwndWrapper' }
      - window_process: { equals: 'EXCEL' }
        window_class: { not_regex: 'XLMAIN' }
      - window_process: { equals: 'WINWORD' }
        window_class: { not_regex: 'OpusApp' }
      - window_process: { equals: 'POWERPNT' }
        window_class: { not_regex: 'PPTFrameClass' }

binding_modes:
  # When enabled, the focused window can be resized via arrow keys or HJKL.
  - name: 'resize'
    keybindings:
      - commands: ['resize --width -2%']
        bindings: ['h', 'left']
      - commands: ['resize --width +2%']
        bindings: ['l', 'right']
      - commands: ['resize --height +2%']
        bindings: ['k', 'up']
      - commands: ['resize --height -2%']
        bindings: ['j', 'down']
      # Press enter/escape to return to default keybindings.
      - commands: ['wm-disable-binding-mode --name resize']
        bindings: ['escape', 'enter']

keybindings:
  # Shift focus in a given direction.
  - commands: ['focus --direction left']
    bindings: ['shift+control+h', 'shift+control+left']
  - commands: ['focus --direction right']
    bindings: ['shift+control+l', 'shift+control+right']
  - commands: ['focus --direction up']
    bindings: ['shift+control+k', 'shift+control+up']
  - commands: ['focus --direction down']
    bindings: ['shift+control+j', 'shift+control+down']

  # Move focused window in a given direction.
  - commands: ['move --direction left']
    bindings: ['shift+alt+h', 'shift+alt+left']
  - commands: ['move --direction right']
    bindings: ['shift+alt+l', 'shift+alt+right']
  - commands: ['move --direction up']
    bindings: ['shift+alt+k', 'shift+alt+up']
  - commands: ['move --direction down']
    bindings: ['shift+alt+j', 'shift+alt+down']zz

  # Resize focused window by a percentage or pixel amount.
  - commands: ['resize --width -2%']
    bindings: ['shift+control+y']
  - commands: ['resize --width +2%']
    bindings: ['shift+control+o']
  - commands: ['resize --height +2%']
    bindings: ['shift+control+i']
  - commands: ['resize --height -2%']
    bindings: ['shift+control+u']

  # As an alternative to the resize keybindings above, resize mode enables
  # resizing via arrow keys or HJKL. The binding mode is defined above with
  # the name 'resize'.
  - commands: ['wm-enable-binding-mode --name resize']
    bindings: ['shift+control+r']

  # Disables window management and all other keybindings until alt+t
  # is pressed again.
  - commands: ['wm-toggle-pause']
    bindings: ['shift+control+t']

  # Change tiling direction. This determines where new tiling windows will
  # be inserted.
  - commands: ['toggle-tiling-direction']
    bindings: ['shift+control+space']


  # Change the focused window to be fullscreen.
  - commands: ['toggle-fullscreen']
    bindings: ['shift+control+m']


  # Close focused window.
  - commands: ['close']
    bindings: ['shift+control+z']

  # Kill GlazeWM process safely.
  #- commands: ['wm-exit']
  #  bindings: ['shift+alt+z']

  # Re-evaluate configuration file.
  - commands: ['wm-reload-config']
    bindings: ['shift+alt+p']

  # Re-draw configuration file.
  - commands: ['wm-redraw']
    bindings: ['shift+alt+;']


  # Launch CMD terminal. Alternatively, use `shell-exec wt` or
  # `shell-exec %ProgramFiles%/Git/git-bash.exe` to start Windows
  # Terminal and Git Bash respectively.
  - commands: ['shell-exec wt']
    bindings: ['shift+control+enter']

  # Focus the workspace that last had focus.
  - commands: ['focus --recent-workspace']
    bindings: ['shift+control+tab']

  # Change focus to a workspace defined in `workspaces` config.
  - commands: ['focus --workspace 1']
    bindings: ['shift+control+q']
  - commands: ['focus --workspace 2']
    bindings: ['shift+control+w']
  - commands: ['focus --workspace 3']
    bindings: ['shift+control+e']
  - commands: ['focus --workspace 4']
    bindings: ['shift+control+r']
  - commands: ['focus --workspace 5']
    bindings: ['shift+control+a']
  - commands: ['focus --workspace 6']
    bindings: ['shift+control+s']
  - commands: ['focus --workspace 7']
    bindings: ['shift+control+d']
  - commands: ['focus --workspace 8']
    bindings: ['shift+control+f']

  # Move the focused window's parent workspace to a monitor in a given
  # direction.
  - commands: ['move-workspace --direction left']
    bindings: ['shift+alt+y']
  - commands: ['move-workspace --direction right']
    bindings: ['shift+alt+o']
  - commands: ['move-workspace --direction up']
    bindings: ['shift+alt+i']
  - commands: ['move-workspace --direction down']
    bindings: ['shift+alt+u']

  # Move focused window to a workspace defined in `workspaces` config.
  - commands: ['move --workspace 1', 'focus --workspace 1']
    bindings: ['shift+alt+q']
  - commands: ['move --workspace 2', 'focus --workspace 2']
    bindings: ['shift+alt+w']
  - commands: ['move --workspace 3', 'focus --workspace 3']
    bindings: ['shift+alt+e']
  - commands: ['move --workspace 4', 'focus --workspace 4']
    bindings: ['shift+alt+r']
  - commands: ['move --workspace 5', 'focus --workspace 5']
    bindings: ['shift+alt+a']
  - commands: ['move --workspace 6', 'focus --workspace 6']
    bindings: ['shift+alt+s']
  - commands: ['move --workspace 7', 'focus --workspace 7']
    bindings: ['shift+alt+d']
  - commands: ['move --workspace 8', 'focus --workspace 8']
    bindings: ['shift+alt+f']
